services:
#  db:
#    image: postgres
#    restart: always
#    container_name: pg_container
#    environment:
#      POSTGRES_USER: ahmed
#      POSTGRES_PASSWORD: potato
#      POSTGRES_DB: books_shelf
#    user: postgres
#    volumes:
##      - ./init.sql:/docker-entrypoint-initdb.d/init.sql <== To init DB
#      - local_pgdata:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres"]
#      interval: 1s
#      timeout: 5s
#      retries: 10
#    ports:
#      - "5432:5432"
#  pgadmin:
#    container_name: pgadmin4_container
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: asonouno@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: potato
#      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
#    ports:
#      - "5050:80"
#    depends_on:
#      db:
#        condition: service_healthy
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin
  api:
    build: .
    restart: always
    ports:
      - "8080:8080"
#    depends_on:
#      db:
#        condition: service_healthy
#    links:
#      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://babar.db.elephantsql.com:5432/gtsfkczj
volumes:
  local_pgdata:
  pgadmin-data:
